DisablePathCorrection = false
EnablePathEscape = false
FireMethodAllowed = false
DisableBodyConsumptionOnUnmarshal = false
TimeFormat = "Mon,02 Jan 2006 15:04:05 GMT"
Charaset = "UTF-8"

[Other]
    MyServerName = "iris"